keys:
  - &devbox age1kyd7dzxtgte0rcd0nj3chfvcfvammhywe63f25tlsrf8knhf3u8sxp8z9n
  - &chromebook age14hkwan2d4znmt5rhvkk74l2cs0lslnzldt9pct7cwv2jts2ztf6s87l8qn

creation_rules:
  - path_regex: secrets/devbox\.yaml$
    key_groups:
      - age:
          - *devbox

  - path_regex: secrets/chromebook\.yaml$
    key_groups:
      - age:
          - *devbox
          - *chromebook
