# sops-nix configuration
# See: https://github.com/Mic92/sops-nix
#
# To use:
# 1. Generate age key: age-keygen -o ~/.config/sops/age/keys.txt
# 2. Add public key below
# 3. Create encrypted secrets: sops secrets/devbox.yaml
#
# keys:
#   - &devbox age1...your-public-key...
#
# creation_rules:
#   - path_regex: secrets/devbox\.yaml$
#     key_groups:
#       - age:
#           - *devbox
